### ISSUE TITLE
aya,开放一个接口？

### ISSUE THREAD

**Issue by big-tooth** [Brx86/DingZhen#1]
想你的云山鸦了

**Comment by Brx86** [comment]
我原本打算把图片都放在7bu上面的，但目前还不能分类存放，以后会开放的（或者先放coding上试试）
![图片](https://bu.dusays.com/2022/04/03/db793442f495a.png)

**Comment by Brx86** [comment]
刚刚没啥事就把图片同步到coding上了，现在开放接口：
http://82.156.27.226:5557/randomdj

可选参数：r（默认为1）
r=0时，接口会直接307重定向到coding的图片地址
其他情况，接口会返回图片链接

示例：
```bash
$ curl -s "http://82.156.27.226:5557/randomdj?r=0"
输出：
{"status":"ok","url":"https://ayatale.coding.net/p/picbed/d/DingZhen/git/raw/main/src/917021660f75098cba21f16aa3d7a2ae.jpg"}
```

**Comment by Brx86** [comment]
已部署[接口](https://github.com/Brx86/DingZhen/blob/api/README.md)

## Api接口：
https://api.aya1.top/randomdj

| 参数名 | 类型   | 是否必须 | 说明                |
| ------ | ------ | -------- | ------------------- |
| r      | string | 否       | 值为0时不进行重定向 |

示例：

    直接访问 https://api.aya1.top/randomdj 跳转到图片地址
    访问 https://api.aya1.top/randomdj?r=0 时，返回json

```bash
$ curl -s "https://api.aya1.top/randomdj?r=0"
输出：
{"status":"ok","url":"https://ayatale.coding.net/p/picbed/d/DingZhen/git/raw/main/src/917021660f75098cba21f16aa3d7a2ae.jpg"}
```
