### ISSUE TITLE
起一个有意义的文件名

### ISSUE THREAD

**Issue by Akarinnnnn** [Brx86/DingZhen#2]
比如这张，起名叫“鬻盐丁真”
![01e641f531adcbef4de29dd2e9af2edda1cc9fd2](https://user-images.githubusercontent.com/43724908/164708318-8af547b2-58ef-4403-a96d-4fea89fd2469.jpg)

**Comment by Brx86** [comment]
hash作为文件名可以起到一定程度的去重作用，之前也有想过给每张图片手动打上标签，但工作量太大，也就一直没去做（其实就是懒233）

**Comment by Akarinnnnn** [comment]
那就只给新增的图片命名吧，按 hash-描述 也行

**Comment by Brx86** [comment]
貌似已经有个挺好的网页前端了，或许你可以看一下（别问我为什么不做，问就是懒且不会） 

http://www.yiyandingzhen.top/

------2022.05.05更新------
现在作者公开了Github仓库
https://github.com/PencilCore/yiyandingzhen

每个图片都打上了标签，api可以搜索，前端也很好看……这位大佬的网站果然完美的满足了需求，那我就可以继续咕咕了（逃
